const knowledgebase = {
  title: "Chess Knowledge Base",
  description: "Structured chess principles and training guidance for analysis and coaching.",
  silmanImbalances: [
    "Superior minor piece - Knight vs bishop advantages in specific positions",
    "Pawn structure - Doubled, isolated, backward, passed pawns and chains",
    "Space - Territory control and piece mobility",
    "Material - Piece count and exchange values",
    "Control of a key file - Open files and heavy piece coordination",
    "Control of a hole/weak square - Outposts and weak squares in opponent's camp",
    "Lead in development - Piece activity and tempo advantage",
    "Initiative (and Tempo) - Forcing moves and maintaining pressure",
    "King safety - Castling, pawn shield, escape squares",
    "Statics vs. Dynamics - Permanent vs temporary factors",
  ],
  finesThirtyPrinciples: {
    opening: [
      "Open with a center pawn",
      "Develop with threats",
      "Develop knights before bishops",
      "Don't move the same piece twice if you can help it",
      "Make as few pawn moves as possible",
      "Don't bring your queen out too early",
      "Castle as soon as possible, preferably on the kingside",
      "Play to get control of the center",
      "Try to maintain at least one pawn in the center",
      "Don't sacrifice without a clear and adequate reason",
    ],
    middlegame: [
      "Have all your moves fit into a definite plan",
      "When you are ahead in material, exchange as many pieces as possible, especially queens",
      "Avoid doubled, isolated, or backward pawns",
      "In cramped positions, free yourself by exchanging",
      "Don't expose your king while the enemy queen is still on the board",
      "All combinations are based on a double attack",
      "When your opponent has one or more pieces exposed, look for a combination",
      "To attack the enemy king, you must first open a file (or less often a diagonal) to gain access for your heavy pieces",
      "Centralize the action of all your pieces",
      "The best defense is a counterattack",
    ],
    endgame: [
      "To win without pawns, you must be a rook or two minor pieces ahead",
      "The king must be active in the ending",
      "Passed pawns must be pushed",
      "The easiest endings to win are pure pawn endings",
      "If you are only one pawn ahead, trade pieces but not pawns",
      "Don't place pawns on the same color squares as your bishop",
      "A bishop is better than a knight in all but blocked pawn positions",
      "It is worth a pawn to get a rook on the seventh rank",
      "Rooks belong behind passed pawns",
      "Blockade passed pawns with the king",
    ],
  },
  additionalEndgamePrinciples: [
    {
      quote: "Endings of one rook and pawns are about the most common sort of endings arising on the chess board. Yet, though they do occur so often, few have mastered them thoroughly. They are often of a very difficult nature, and sometimes while apparently very simple they are in reality extremely intricate.",
      author: "Jose Capablanca",
    },
    {
      quote: "It is a well-known phenomenon that the same amateur who can conduct the middle game quite creditably, is usually perfectly helpless in the end game. One of the principal requisites of good chess is the ability to treat both the middle and end game equally well.",
      author: "Aaron Nimzowitsch",
    },
    {
      quote: "The business of the endgame is maneuvering to control critical squares, advancing or blockading passed pawns, preparing a breakthrough by the king, or exploiting the subtle superiority of one piece over another.",
      author: "Pal Benko",
    },
    "Capablanca's Principle of Two Weaknesses: Create multiple weaknesses to stretch the opponent's defense.",
    "In the Chess Endgame, the king becomes a dominant force. Centralize your king for support and control.",
    "The great mobility of the King forms one of the chief characteristics of all endgame strategy. In the middle game the King is a mere 'super', in the endgame on the other hand – one of the 'principals'. We must therefore develop him; bring him nearer to the fighting line.",
    "The king, which during the opening and middle game stage is often a burden because it has to be defended, becomes in the endgame a very important and aggressive piece, and the beginner should realize this, and utilize his king as much as possible.",
    "In a rook and pawn ending, the rook must be used aggressively. It must either attack enemy pawns, or give active support to the advance of one of its own pawns to the queening square.",
    "The opposition is key in king-and-pawn endgames. The player not to move often controls critical squares.",
    "Passed pawns are the backbone of endgame strategy. Create and advance them.",
    "The rule of the square: If the opposing king can enter the square drawn from the pawn to promotion, it can catch the pawn.",
    "In rook endgames, rooks belong behind passed pawns.",
    "Zugzwang: Forcing your opponent to move when any move worsens their position.",
    "Simplify when ahead, but not too early; avoid giving counterplay.",
    "Precise calculation is critical in endgames.",
    "A player can sometimes afford the luxury of an inaccurate move, or even a definite error, in the opening or middle game without necessarily obtaining a lost position. In the endgame … an error can be decisive, and we are rarely presented with a second chance.",
    "Patience and prophylactic thinking are vital in endgames.",
    "If you are weak in the endgame, you must spend more time analyzing studies. In your training games, you must aim at transposing to endgames which will help you to acquire the requisite experience.",
    "Do not hurry in the endgame.",
    "Rook vs Bishop: Defending side should put king in the opposite color corner to the bishop.",
    "Rook vs Knight: Trap the knight at the edge (red/yellow zones); defend by keeping knight in the center (green zone).",
    "Opposite color bishop endgames: Attacker should keep pawns on both sides; defender should restrict to one side.",
    "Knight is often stronger than bishop in endgames with pawns on one side.",
  ],
  pawnStructures: [
    { name: "Doubled Pawns", pros: ["May control key squares", "Semi-open file"], cons: ["Static weakness", "Reduced mobility"] },
    { name: "Backward Pawn", pros: ["Rare tactical opportunities"], cons: ["Weak square in front", "Target for attack"] },
    { name: "Passed Pawn", pros: ["Promotes to queen", "Diverts enemy pieces"], cons: ["May need protection", "Can be blockaded"] },
    { name: "Pawn Chain", pros: ["Strong structure", "Space control"], cons: ["Base can be attacked", "Inflexible"] },
    { name: "Isolated Pawn", pros: ["Open files for pieces", "Central control"], cons: ["Weakness", "Requires piece protection"] },
  ],
  tacticalMotifs: [
    { name: "Pin", description: "Attacking a piece that cannot move without exposing a more valuable piece" },
    { name: "Fork", description: "Single piece attacking two or more enemy pieces simultaneously" },
    { name: "Skewer", description: "Forcing a valuable piece to move and capturing a less valuable piece behind it" },
    { name: "Discovered Attack", description: "Moving one piece to reveal an attack from another piece" },
    { name: "Double Attack", description: "Attacking two targets simultaneously" },
    { name: "Deflection", description: "Forcing a piece away from an important duty" },
    { name: "Decoy", description: "Luring a piece to a bad square" },
    { name: "Clearance", description: "Moving a piece to clear a line for another piece" },
    { name: "Interference", description: "Placing a piece between two enemy pieces to disrupt their coordination" },
    { name: "X-ray", description: "Attack through another piece to a target behind it" },
  ],
  strategicGuidelines: {
    savingLostPositions: ["Seek complications", "Avoid exchanges", "Target the king", "Sacrifice if needed", "Improve all pieces", "Play creatively", "Set traps", "Look for stalemates and swindles"],
    winningWonPositions: ["Exchange pieces", "Maintain king safety", "Avoid greed", "Punish bluffs", "Prevent counterplay", "Keep pieces active"],
    endgameRoadmap: ["Activate pieces and king", "Create weak opponent pawns/squares", "Win pawns", "Create and promote passed pawns", "Checkmate", "Stay alert for tactics", "Block or win passed pawns", "Exchange or sacrifice weak pawns", "Cover weak/entry squares"],
    clampChecklist: [
      { letter: "C", principle: "Checks: Does my move allow a devastating check for my opponent?" },
      { letter: "L", principle: "Loose Pieces and Squares: Am I leaving something unprotected?" },
      { letter: "A", principle: "Alignments: Am I creating a dangerous alignment (forks, pins, skewers, discovered attacks)?" },
      { letter: "M", principle: "Mobility Restrictions: Does my move restrict my pieces, making them trappable?" },
      { letter: "P", principle: "Passed Pawns: Does my move allow an unstoppable passed pawn for my opponent?" },
    ],
    chessMood7Q: [
      "What problems does the opponent have?",
      "What problems do I have?",
      "Where am I strong?",
      "Which of my pieces can be happier?",
      "Which pieces do I want to trade?",
      "What is the opponent's next move or plan?",
      "How can I advance (if none of the other six questions have compelling answers)?",
    ],
    openingPrinciples: [
      "Control the center with pawns and pieces",
      "Develop knights before bishops",
      "Castle early for king safety",
      "Don't move the same piece twice without good reason",
      "Don't bring the queen out too early",
      "Connect your rooks",
      "Develop with purpose and threats",
    ],
    weaknesses: ["Weak squares", "Weak pawns", "Exposed king", "Uncoordinated pieces"],
    strengths: ["Active pieces", "Better pawn structure", "King safety", "Initiative"],
    planningGuidelines: ["Improve worst piece", "Create weaknesses", "Control key squares", "Advance passed pawns"],
    selfCorrection: ["Acknowledge errors naturally and thank the user if they point them out.", "Re-analyze with new input and keep the conversation collaborative."],
    handlingComplexity: ["Admit when evaluation is difficult.", "Present multiple perspectives and discuss practical vs. theoretical considerations.", "For sharp tactics, start with obvious ideas, then dig deeper."],
    additionalWisdom: [
      "The pawns are the soul of chess – Francois-Andre Danican Philidor",
      "Every pawn is a potential queen – James Mason",
      "The threat is stronger than the execution – Aaron Nimzowitsch",
      "Capture towards the center – General principle",
      "When in doubt, improve your worst piece – GM advice",
      "Look for checks, captures, and threats – Basic calculation order",
    ],
  },
};

export function getKnowledgeBase() {
  return knowledgebase;
}
